name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev libbz2-dev

      - name: Install Buildozer and Cython
        run: |
          pip install --upgrade Cython==0.29.33 wheel buildozer
          echo "/home/runner/.local/bin" >> $GITHUB_PATH

      - name: Build with Buildozer
        run: |
          export PATH=$PATH:/home/runner/.local/bin
          yes | buildozer -v android debug
        env:
          BUILDOZER_ALLOW_ORG_KIVY_LEMON: 1

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Spaceship-Game-APK
          path: bin/*.apk
